[theme]
primaryColor = "#6C63FF"               # Light purple (accent)
backgroundColor = "#f0f8ff"            # Alice blue / very light blue
secondaryBackgroundColor = "#e6e6fa"   # Lavender
textColor = "#1a1a2e"                  # Deep navy/black-blue text
font = "sans serif"
